# fly.toml app configuration file generated for ip-smtp-proxy on 2024-11-05T00:55:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ip-smtp-proxy'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "certs"
  destination = "/etc/letsencrypt"

[[services]]
  internal_port = 587        # Set the internal port to 587
  protocol = "tcp"

  [[services.ports]]
    port = 587               # Expose port 587 externally

  [[services.tcp_checks]]
    interval = "15s"         # Optional health check interval
    timeout = "2s"
    grace_period = "1m"
    restart_limit = 0
